fixing

diff --git a/wso2apim-publisher/config/wso2am-publisher-conf-entrypoint.yaml b/wso2apim-publisher/config/wso2am-publisher-conf-entrypoint.yaml
--- a/wso2apim-publisher/config/wso2am-publisher-conf-entrypoint.yaml
+++ b/wso2apim-publisher/config/wso2am-publisher-conf-entrypoint.yaml
@@ -34,33 +34,32 @@ data:
 
       # shared artifact directories
 
-      directories=["executionplans","synapse-configs"]
+      # directories=["executionplans","synapse-configs"]
 
-      # if the original directory locations of artifacts to be synced between nodes are empty,
+      # # if the original directory locations of artifacts to be synced between nodes are empty,
 
-      # copy the preserved, default content of these folders to these original locations
+      # # copy the preserved, default content of these folders to these original locations
 
-      # for shared_directory
-      # do
-      #   if test -d ${original_deployment_artifacts}/${shared_directory};
-      #   then
-      #     if [ -z "$(ls -A ${deployment_volume}/${shared_directory})" ]; then
-      #       if ! cp -R ${original_deployment_artifacts}/${shared_directory}/* ${deployment_volume}/${shared_directory};
-      #       then
-      #         echo "Failed to copy the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})" >&2
-      #         exit 1
-      #       fi
-      #       echo "Successfully copied the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})" >&2
+      # for shared_directory in ${directories[@]}; do
+      # if test -d ${original_deployment_artifacts}/${shared_directory};
+      # then
+      #   if [[ -z "$(ls -A ${deployment_volume}/${shared_directory})" ]]; then
+      #     if ! cp -R ${original_deployment_artifacts}/${shared_directory}/* ${deployment_volume}/${shared_directory};
+      #     then
+      #       echo "Failed to copy the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})"
+      #       exit 1
       #     fi
+      #     echo "Successfully copied the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})"
       #   fi
+      # fi
       # done
 
       # # Copying carbon_db
       # if ! test -f /home/wso2carbon/solr/database/WSO2CARBON_DB.mv.db
       # then
-      #   echo "Copying WSO2CARBON_DB.mv.db" >&2
-      #   cp ${WSO2_SERVER_HOME}/repository/database/WSO2CARBON_DB.mv.db /home/wso2carbon/solr/database/
-      # fi
+      #    echo "Copying WSO2CARBON_DB.mv.db" >&2
+      #    cp ${WSO2_SERVER_HOME}/repository/database/WSO2CARBON_DB.mv.db /home/wso2carbon/solr/database/
+      #  fi
 
       # Optimizing WSO2 Carbon Server
 
